import Head from 'next/head'
import Image from 'next/image'
import { MicrophoneIcon, ViewGridIcon } from '@heroicons/react/solid'
import { SearchIcon } from '@heroicons/react/outline'
import Avatar from '../components/Avatar'
import Footer from '../components/Footer'
import { useRef, useState } from 'react'
import { useRouter } from 'next/router'

export default function Home() {
  const [dark, setDark] = useState(false)
  const router = useRouter()
  const searchInputRef = useRef(null)
  const search = (e) => {
    e.preventDefault()

    const term = searchInputRef.current.value
    if (!term) {
      return
    }

    router.push(`/search?term=${term}`)
  }

  return (
    <div className={`${dark && 'dark'}`}>
      <div className="flex flex-col min-h-screen dark:bg-slate-800  overflow-hidden">
        <Head>
          <title>Google Clone</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        {/* Header */}
        <header className="flex w-full justify-between p-4 text-sm dark:bg-slate-800 dark:text-white">
          <div className="flex space-x-4 items-center mr-3">
            <p className="link">About</p>
            <p className="link">Store</p>
          </div>

          <div className="flex space-x-4 items-center">
            <p className="link">Gmail</p>
            <p className="link">Images</p>
            <ViewGridIcon className="hidden sm:inline-flex h-10 w-10 rounded-full transition-all duration-300 ease-linear hover:bg-gray-200 cursor-pointer p-2 text-gray-500 dark:text-white" />
            <Avatar url="https://lh3.googleusercontent.com/ogw/ADea4I4zUFn_m3z7aBUo3Jw7TNIo--g0xvl8hLmahKcS=s64-c-mo" />
          </div>
        </header>

        {/* Body */}
        <form className="flex flex-col items-center mt-4 flex-grow">
          <Image
            src="https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png"
            width={300}
            height={100}
          />

          <div className="flex w-4/5 max-w-md border border-gray-300 px-3 py-3 items-center rounded-full hover:shadow-lg focus-within:shadow-lg sm:max-w-xl lg:max-w-2xl mt-6 dark:bg-slate-700">
            <SearchIcon className="h-4 text-gray-400 dark:text-white" />
            <input
              type="text"
              className="focus:outline-none flex-grow dark:bg-slate-700 dark:text-white ml-2"
              ref={searchInputRef}
            />
            <MicrophoneIcon className="h-4 text-gray-500 dark:text-white" />
          </div>

          <div className="flex justify-center mt-8 sm:space-x-4 flex-col space-y-4 sm:space-y-0 sm:flex-row">
            <button type="submit" className="btn" onClick={search}>
              Google Search
            </button>
            <button className="btn" onClick={search}>
              I&apos;m Feeling Lucky
            </button>
          </div>
        </form>

        <div className='relative'>
          <Footer />
          <p
            className="link absolute top-3 right-5 text-[16px] text-gray-500 dark:text-white"
            onClick={() => setDark(!dark)}
          >
            Dark Theme: {dark ? 'On' : 'Off'}
          </p>
        </div>

      </div>
    </div>
  )
}
